In [2]:
import pandas as pd
import numpy as np
data = pd.read_excel('school_enroll_unit_admission.xlsx')
data.head(5)

id            enroll_unit_id                 school_id  stu_province_id  \
0   1  52ac2e9a747aec013fcf5190  52ac2e9a747aec013fcf5190     510000000000   
1   2  52ac2e9a747aec013fcf5190  52ac2e9a747aec013fcf5190     510000000000   
2   3  52ac2e9a747aec013fcf5190  52ac2e9a747aec013fcf5190     510000000000   
3   4  52ac2e9a747aec013fcf5190  52ac2e9a747aec013fcf5190     510000000000   
4   5  52ac2e9a747aec013fcf5190  52ac2e9a747aec013fcf5190     510000000000   

   enroll_year batch_name  admission_count  min_score  min_score_rank  \
0         2020      本科第一批              NaN        646               1   
1         2019      本科第一批             23.0        658              38   
2         2018      本科第一批             24.0        642              39   
3         2017      本科第一批              NaN        650              25   
4         2020      本科第一批              NaN        695              71   

   min_score_diff  avg_score  avg_score_rank  max_score  max_score_rank  \
0           119.0        NaN             NaN        NaN             NaN   
1           118.0        NaN             NaN        NaN             NaN   
2            89.0      648.0            37.0      663.0            32.0   
3           113.0        NaN             NaN      668.0            10.0   
4           166.0        NaN             NaN        NaN             NaN   

          create_time         update_time  wenli  
0 2021-03-21 17:30:04 2021-03-21 17:30:04      1  
1 2021-03-21 17:30:05 2021-03-21 17:30:05      1  
2 2021-03-21 17:30:05 2021-03-21 17:30:05      1  
3 2021-03-21 17:30:05 2021-03-21 17:30:05      1  
4 2021-03-21 17:30:06 2021-03-21 17:30:06      2

In [28]:
# data_2020 = data[data['enroll_year']==2020]
# data_2019 = data[data['enroll_year']==2019]
# data_2018 = data[data['enroll_year']==2018]
# data_2017 = data[data['enroll_year']==2017]
data2=data[['school_id','enroll_year','batch_name','min_score_diff','wenli','min_score','min_score_rank']]

In [29]:
data2 =pd.get_dummies(data2,columns=['enroll_year','batch_name','wenli'])

In [30]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17297 entries, 0 to 17296
Data columns (total 13 columns):
school_id           17297 non-null object
min_score_diff      15099 non-null float64
min_score           17297 non-null int64
min_score_rank      17297 non-null int64
enroll_year_2017    17297 non-null uint8
enroll_year_2018    17297 non-null uint8
enroll_year_2019    17297 non-null uint8
enroll_year_2020    17297 non-null uint8
batch_name_本科第一批    17297 non-null uint8
batch_name_本科第二批    17297 non-null uint8
batch_name_高职专科批    17297 non-null uint8
wenli_1             17297 non-null uint8
wenli_2             17297 non-null uint8
dtypes: float64(1), int64(2), object(1), uint8(9)
memory usage: 692.6+ KB


In [31]:
data3 =data2.dropna()

In [32]:
data3.head()

school_id  min_score_diff  min_score  min_score_rank  \
0  52ac2e9a747aec013fcf5190           119.0        646               1   
1  52ac2e9a747aec013fcf5190           118.0        658              38   
2  52ac2e9a747aec013fcf5190            89.0        642              39   
3  52ac2e9a747aec013fcf5190           113.0        650              25   
4  52ac2e9a747aec013fcf5190           166.0        695              71   

   enroll_year_2017  enroll_year_2018  enroll_year_2019  enroll_year_2020  \
0                 0                 0                 0                 1   
1                 0                 0                 1                 0   
2                 0                 1                 0                 0   
3                 1                 0                 0                 0   
4                 0                 0                 0                 1   

   batch_name_本科第一批  batch_name_本科第二批  batch_name_高职专科批  wenli_1  wenli_2  
0                 1                 0                 0        1        0  
1                 1                 0                 0        1        0  
2                 1                 0                 0        1        0  
3                 1                 0                 0        1        0  
4                 1                 0                 0        0        1

In [33]:
x = data3.drop(columns=['school_id','min_score'])

In [34]:
y=data3['min_score'].values.reshape(-1,1)

In [35]:
x.ndim

2

In [36]:
y.ndim

2

In [37]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 41)
x_train.shape

(12079, 11)

In [38]:
# from sklearn.preprocessing import MinMaxScaler
# minmax_scaler=MinMaxScaler()
# minmax_scaler.fit(x)   #进行内部拟合，内部参数会发生变化
# x=minmax_scaler.transform(x)
# x

In [39]:
from sklearn.linear_model import LinearRegression
LR_reg=LinearRegression()
#进行拟合
LR_reg.fit(x_train,y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [15]:
# from sklearn.metrics import mean_squared_error
# minmax_scaler=MinMaxScaler()
# minmax_scaler.fit(x_test)   #进行内部拟合，内部参数会发生变化
# scaler_housing=minmax_scaler.transform(x_test)
# preds=LR_reg.predict(x_test)   #输入数据进行预测得到结果
# mse=mean_squared_error(preds,y_test)   #使用均方误差来评价模型好坏，可以输出mse进行查看评价值
# mse

C:\Users\NICAI\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


118.03561079220462

In [16]:
# LR_reg.score(x_test,y_test)

0.992643195026812

In [40]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt

In [50]:
# Fit regression model
regr_1 = DecisionTreeRegressor(max_depth=2)
regr_2 = DecisionTreeRegressor(max_depth=5)
regr_3 = DecisionTreeRegressor(max_depth=10)
regr_1.fit(x_train, y_train)
regr_2.fit(x_train, y_train)
regr_3.fit(x_train, y_train)
# Predxictx

y_1 = regr_1.predict(x_test)
y_2 = regr_2.predict(x_test)
y_3 = regr_3.predict(x_test)


In [54]:
from sklearn.model_selection import GridSearchCV
parameters ={'max_depth':[i for  i  in range(2,100)]}
clf=DecisionTreeRegressor()
grid_serch = GridSearchCV(clf,parameters,scoring='r2',cv=5)
grid_serch.fit(x_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_depth': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='r2', verbose=0)

In [55]:
grid_serch.best_params_

{'max_depth': 48}

In [42]:
y_1

array([481.82046649, 587.99308118, 481.82046649, ..., 240.94180704,
       481.82046649, 481.82046649])

In [57]:
# Fit regression model
regr_4 = DecisionTreeRegressor(max_depth=48)

regr_4.fit(x_train, y_train)





DecisionTreeRegressor(criterion='mse', max_depth=48, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [58]:
from sklearn.metrics import r2_score
r2= r2_score(y_test,regr_4.predict(x_test))

In [59]:
r2

0.9999698890442659

In [43]:
y_2

array([525.0702439 , 578.01590457, 463.58624454, ..., 208.13700384,
       525.0702439 , 487.76020408])

In [44]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,roc_curve

In [45]:
y_test

array([[537],
       [559],
       [463],
       ...,
       [221],
       [539],
       [508]], dtype=int64)

In [46]:
y_1 = y_1.astype(int)
y_1

array([481, 587, 481, ..., 240, 481, 481])

In [24]:
#score = precision_score(y_test,y_1)

In [25]:
y_1 = regr_2.predict(x_test)

In [51]:
data3['min_scoreyuce']=regr_2.predict(x)
data3['min_scoreyuce2']=regr_1.predict(x)
data3['min_scoreyuce3']=regr_3.predict(x)


C:\Users\NICAI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\NICAI\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\NICAI\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.

In [52]:
data3[['min_score','min_scoreyuce','min_scoreyuce2','min_scoreyuce3']]  #对比观察。

min_score  min_scoreyuce  min_scoreyuce2  min_scoreyuce3
0            646     643.033113      587.993081      644.000000
1            658     643.033113      587.993081      658.040000
2            642     613.877193      587.993081      635.846154
3            650     643.033113      587.993081      650.000000
4            695     673.705128      587.993081      692.200000
5            706     673.705128      587.993081      705.500000
6            690     673.705128      587.993081      686.333333
7            688     673.705128      587.993081      686.333333
8            654     673.705128      587.993081      654.000000
9            666     673.705128      587.993081      666.000000
10           649     643.033113      587.993081      647.952381
11           652     643.033113      587.993081      652.000000
12           694     673.705128      587.993081      692.200000
13           705     673.705128      587.993081      705.500000
14           687     673.705128      587.993081      686.333333
15           687     673.705128      587.993081      686.333333
16           639     643.033113      587.993081      644.000000
17           650     643.033113      587.993081      658.040000
18           637     613.877193      587.993081      627.250000
19           638     643.033113      587.993081      641.000000
20           691     673.705128      587.993081      692.200000
21           703     673.705128      587.993081      702.500000
22           684     673.705128      587.993081      686.333333
23           674     673.705128      587.993081      674.400000
24           628     643.033113      587.993081      626.500000
25           644     643.033113      587.993081      647.952381
26           630     613.877193      587.993081      628.333333
27           633     643.033113      587.993081      634.750000
28           682     673.705128      587.993081      681.400000
29           691     673.705128      587.993081      692.000000
...          ...            ...             ...             ...
17250        196     175.363636      240.941807      196.400000
17251        227     208.137004      240.941807      226.966667
17252        361     369.478261      368.886870      361.000000
17253        211     208.137004      240.941807      211.692308
17254        283     280.116279      240.941807      284.560000
17261        246     242.025704      240.941807      253.076923
17262        265     242.025704      240.941807      263.763158
17265        370     389.736842      481.820466      368.717391
17266        345     346.172524      481.820466      345.181818
17267        292     277.453659      240.941807      292.000000
17268        249     280.116279      240.941807      250.833333
17269        242     242.025704      240.941807      241.052632
17270        222     208.137004      240.941807      220.156627
17272        151     175.363636      240.941807      151.000000
17275        151     175.363636      240.941807      151.000000
17277        348     346.172524      481.820466      347.800000
17278        296     305.523256      368.886870      296.000000
17279        303     277.453659      240.941807      302.333333
17280        268     280.116279      240.941807      266.800000
17281        181     175.363636      240.941807      181.571429
17282        203     208.137004      240.941807      205.365079
17283        255     280.116279      240.941807      250.833333
17284        203     242.025704      240.941807      202.133333
17286        231     242.025704      240.941807      231.125000
17287        319     302.648148      240.941807      317.857143
17288        248     242.025704      240.941807      245.963303
17291        351     346.172524      481.820466      351.096774
17292        281     277.453659      240.941807      281.416667
17293        284     280.116279      240.941807      285.333333
17294        170     175.363636      240.941807      169.333333

[15099 rows x 4 columns]